version: '3.7'

services:  
  webapi:
    build:
      context: ./WebApplication1
    ports:
      - "2289:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=mydatabase;User Id=myuser;Password=mypassword

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase 
 